'\" t
.\"     Title: command-not-found
.\"    Author: Pavol Rusnak <stick@gk2.sk>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/08/2019
.\"    Manual: https://en.opensuse.org/Scout
.\"    Source: https://github.com/openSUSE/scout 0.2.7
.\"  Language: English
.\"
.TH "COMMAND\-NOT\-FOUND" "1" "08/08/2019" "https://github\&.com/openSUSE/" "https://en\&.opensuse\&.org/Sc"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
command-not-found \- A command\-not\-found handler
.SH "SYNOPSIS"
.HP \w'\fBcommand\-not\-found\fR\ 'u
\fBcommand\-not\-found\fR {binary_name} {repository}
.SH "ARGUMENTS"
.PP
The following arguments are required:
.PP
\fBbinary_name\fR
.RS 4
The name of the binary you are looking for\&.
.RE
.PP
\fBrepository\fR
.RS 4
The name of the repository to search\&. For most cases, use zypp
.RE
.SH "DESCRIPTION"
.PP
the command\-not\-found handler searches the package a missing command belongs to\&.
.PP
The handler is integrated into the bash(1) and zsh(1) shells and doesn\*(Aqt need to be called directly\&. Just type the name of a command in your favourite shell and you\*(Aqll get a result\&.
.PP
If you consider the c\-n\-f handler useless, just add
unset command_not_found_handle
to your profile or remove the command\-not\-found package\&.
.PP
The handler doesn\*(Aqt call the command\-not\-found binary directly, it only prints info about it\&. If you want to invoke it automatically, just add
export COMMAND_NOT_FOUND_AUTO=1
to your bash profile\&.
.PP
If you want to install found packages, add
export COMMAND_NOT_FOUND_INSTALL=1
to your bash profile\&.
.SH "EXAMPLE: NORMAL USAGE"
.PP
For example you want to try
blender, because you have heard that is an amazing program\&. So just type blender in your shell:
.sp
.if n \{\
.RS 4
.\}
.nf
$ \fBblender\fR
.fi
.if n \{\
.RE
.\}
.PP
You get the following output:
.sp
.if n \{\
.RS 4
.\}
.nf
The program \*(Aqblender\*(Aq can be found in the following package:
  * blender [ path: /usr/bin/blender, repository: zypp (openSUSE 11\&.1\-0) ]

Try installing with:
    sudo zypper install blender

bash: blender: command not found
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
scout(1)
.SH "AUTHOR"
.PP
\fBPavol Rusnak\fR <\&stick@gk2\&.sk\&>
.RS 4
Developer
.RE
