#!/bin/sh

for i in bin*.txt; do
    f=`basename $i .txt`
    TMP=`mktemp`
    echo -n "Processing $f ... "
    ./gensimple.py $f.txt binary bin path pkg > $TMP
    sqlite3 -batch $f.db < $TMP
    echo 'done'
    rm $TMP
done
