#!/bin/bash

INSTALL_CMD='sudo zypper install'

if [[ ${1} == "" ]]; then
    exit 1
fi

if [[ "$(which scout)" == "" ]]; then
    exit 2
fi

module_name=$(echo ${1} | sed 's/No module named //')

package=$(/usr/bin/scout -f csv python ${module_name} | grep -v '^"repo' | cut -d ';' -f 2 | tr -d '"' | sort -u)

package_cnt=$(echo ${package} | wc -w)

echo
echo
case ${package_cnt} in
    0)
        echo "No package containing module '${module_name}' was found by scout"
    ;;
    1)
        echo "Module '${module_name}' was found in the package ${package}. You can install it by:"
        echo "$INSTALL_CMD zypper install ${package}"
    ;;
    *)
        echo "The selected module was found in one of several packages:"
        echo "${package}"
        echo "$INSTALL_CMD <selected_package>"
    ;;
esac
