#!/bin/bash

INSTALL_CMD='sudo zypper install'

if [[ ${1} == "" ]]; then
    echo "Usage ${0} python_module"
    exit 1
fi

if [[ "$(which scout)" == "" ]]; then
    exit 2
fi

module_name=$(echo ${1} | sed 's/No module named //')

packages=$(/usr/bin/scout -f csv python ${module_name} | grep -v '^"repo' | cut -d ';' -f 2 | tr -d '"' | sort -u)

packages_cnt=$(echo ${modules} | wc -w)

echo -e "\n"
case ${packages_cnt} in
    0)
    echo "No package which contains the module '${module_name}' was found by scout."
    ;;
    1)
    echo "The '${module_name}' was found package ${packages}. You can install it by:"
    echo "${INSTALL_CMD} ${packages}"
    ;;
    *)
    echo "The '${module_name}' was found in one of those packages:"
    echo "${packages}"
    echo "$INSTALL_CMD <selected_package>"
    ;;
esac
